Tunefaceweb/urls.py
from django.contrib import admin
from django.urls import path
from .views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
]

Tunefaceweb/models.py
from django.db import models
from .settings import FIRESTORE_DB


class UsuarioTuneFace:
    def __init__(self, nombre, local, imagenes=None, canciones=None):
        self.nombre = nombre
        self.local = local
        self.imagenes = imagenes
        self.canciones = canciones

    def to_dict(self):
        return {
            "nombre": self.nombre,
            "local": self.local,
            "imagenes": self.imagenes,
            "canciones": self.canciones,
        }

    @staticmethod
    def from_dict(data):
        return UsuarioTuneFace(
            nombre=data.get("nombre"),
            local=data.get("local"),
            imagenes=data.get("imagenes"),
            canciones=data.get("canciones"),
        )

    def __str__(self):
        return self.nombre

Tunefaceweb/forms.py
from django import forms
from firebase_admin import firestore
from django.utils.safestring import mark_safe
from django.core.exceptions import ValidationError


db = firestore.client()

class SongSelectMultipleWidget(forms.SelectMultiple):
    def create_option(self, name, value, label, selected, index, subindex=None, attrs=None):
        if value is None:
            value = ''
        option_dict = super().create_option(name, value, label, selected, index, subindex=subindex, attrs=attrs)
        # Procesar HTML seguro en el label
        if label and isinstance(label, str):
            option_dict['label'] = mark_safe(label)
        return option_dict

class MultipleFileInput(forms.ClearableFileInput):
    allow_multiple_selected = True  

class MultipleFileField(forms.FileField):
    def __init__(self, *args, **kwargs):
        kwargs.setdefault("widget", MultipleFileInput(attrs={'multiple': True, 'class': 'form-control form-group', 'id': 'imagenes'}))
        super().__init__(*args, **kwargs)

    def clean(self, data, initial=None):
        single_file_clean = super().clean
        if isinstance(data, (list, tuple)):
            result = [single_file_clean(d, initial) for d in data]
        else:
            result = [single_file_clean(data, initial)]
        return result
    
def obtener_opciones_locales():
    docs = db.collection('locales').stream()
    opciones = [(doc.id, doc.to_dict().get('nombre', 'Sin Nombre')) for doc in docs]
    if not opciones: 
        opciones.append(('', 'No hay locales disponibles'))
    return opciones

def obtener_opciones_canciones():
    docs = db.collection('canciones').stream()
    opciones = []
    for doc in docs:
        data = doc.to_dict()
        titulo = data.get('titulo', 'Sin Título')
        imagen_url = data.get('imagen_url', '')
        label = f'<img src="{imagen_url}" style="width:30px; height:30px; margin-right:10px;"> {titulo}' if imagen_url else titulo
        opciones.append((doc.id, label)) 
    if not opciones:
        opciones.append(('', 'No hay canciones disponibles'))
    return opciones

def clean_canciones(self):
        canciones = self.cleaned_data.get('canciones', [])
        if len(canciones) > 3:
            raise ValidationError('No puedes seleccionar más de 3 canciones.')
        return canciones

def clean_imagenes(self):
        files = self.files.getlist('imagenes')  
        if not files:
            raise forms.ValidationError("No se seleccionó ninguna imagen.")
        for file in files:
            if not file.content_type.startswith('image/'):
                raise forms.ValidationError(f"El archivo {file.name} no es una imagen válida.")
        return files

class UsuarioTunefaceForm(forms.Form):
    CANCIONESCHOICES = obtener_opciones_canciones()
    LOCALCHOICES = obtener_opciones_locales()

    nombre = forms.CharField(max_length=100, label="Nombre", widget=forms.TextInput(attrs={'class': 'form-control form-group'}))
    local = forms.ChoiceField(
        choices=LOCALCHOICES,
        label="Local",
        widget=forms.Select(attrs={
            'class': 'form-select form-group',
            'aria-label': 'Default select example',
        }),
    )
    imagenes = MultipleFileField(
        label="Imágenes",
        required=False  # Cambia a True si es obligatorio
    )
    canciones = forms.MultipleChoiceField(
        choices=CANCIONESCHOICES,
        widget=SongSelectMultipleWidget(),
        label="Canciones"
    )

    

Tunefaceweb/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import FormView
from django.contrib import messages
from google.cloud import storage
from firebase_admin import firestore
from .forms import UsuarioTunefaceForm
from django.conf import settings
from django.core.exceptions import ValidationError
import cloudinary.uploader
import uuid
import os
from django.urls import reverse_lazy
import logging

#LOGS
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)
# Instancia de Firestore
db = firestore.client()

# Configuración para Firebase Storage
#storage_client = storage.Client()
#bucket_name = "tu-bucket-name" ##cambiar 
#bucket = storage_client.bucket(bucket_name)

#def upload_image(file):
#    if not file.content_type.startswith('image/'):
#        raise ValidationError("El archivo subido no es una imagen válida.")
    
#    unique_name = f"{uuid.uuid4()}-{file.name}"
#    blob = bucket.blob(f"usuarios/{unique_name}")
#    blob.upload_from_file(file)
#    blob.make_public()
#    return blob.public_url

def upload_image(file): # Subir la imagen a cloudinary / cambiar luego por metodo firestore
    if not file.content_type.startswith('image/'):
        raise ValidationError("El archivo subido no es una imagen válida.")
    
    # Subir la imagen a Cloudinary
    response = cloudinary.uploader.upload(file)
    return response['secure_url']

def index(request):
    canciones_docs = db.collection('canciones').stream()
    if request.method == 'POST':
        logger.info(f'Archivos recibidos: {request.FILES}')
        form = UsuarioTunefaceForm(request.POST, request.FILES)
        if form.is_valid():
            # Preparar los datos para Firestore
            nombre = form.cleaned_data['nombre']
            local = form.cleaned_data['local']
            canciones = form.cleaned_data['canciones']
            if len(canciones) > 3:
                messages.error(request, 'Solo puedes seleccionar hasta 3 canciones.')
                return redirect('index')
            imagenes = request.FILES.getlist('imagenes')

            # Subir la imagen 
            image_urls = []
            for imagen in imagenes:
                print(imagen.name)
                image_url = upload_image(imagen)
                image_urls.append(image_url)

            # Guardar en Firestore
            db.collection('usuarios').add({
                'nombre': nombre,
                'local': local,
                'canciones': canciones,
                'imagenes': image_urls, 
            })

            messages.success(request, 'Usuario ingresado correctamente')
            return redirect('index')
        else:
            logger.error('Error al ingresar usuario: %s', form.errors)
            messages.error(request, 'Error al ingresar usuario')
    else:
        form = UsuarioTunefaceForm()

    # Preparar el contexto de canciones
    canciones_context = [
        {
            'id': doc.id,  # ID del documento
            'titulo': doc.to_dict().get('titulo', 'Sin Título'),
            'imagen_url': doc.to_dict().get('imagen_url', ''),
        }
        for doc in canciones_docs
    ]

    # Combinar los contextos
    context = {
        'form': form,
        'canciones': canciones_context,
    }

    return render(request, 'index.html', context)

Tunefaceweb/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TuneFace</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</head>
<style>
    select option div {
    display: flex;
    align-items: center;
}

select option img {
    margin-right: 10px;
    width: 30px;
    height: 30px;
}
.navbar {
    background-color: #261842 !important; /* Fondo oscuro */
    color: white !important; /* Texto blanco */
}

.navbar .navbar-brand,
.navbar .nav-link {
    color: white !important; /* Color de los enlaces */
}

.navbar .nav-link:hover {
    color: #00d1ff !important; /* Efecto hover en los enlaces */
}

body {
    background-color: #1a1a1e; /* Fondo del resto de la página */
}
</style>
<body style="background-color: #1a1a1e;">
    {% if messages %}
        <div class="messages justify-content-center d-flex text-white" style="background-color: #034a8b;">
            {% for message in messages %}
                <div class="message text-white {{ message.tags }}">{{ message }}</div>
            {% endfor %}
        </div>
    {% endif %}
    <nav class="navbar navbar-expand-lg">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">
                <img src="https://res.cloudinary.com/druu3mtg7/image/upload/v1737558032/Logo_sv7rts.png" alt="Logo" width="70" height="68" class="d-inline-block align-text-top">
              </a>
        </div>
      </nav>
    <!--Formulario-->
        <div class="row">
          <div class="col-4"></div>
          <div class="col">
            <div class="row justify-content-center">
                <form class="row g-3 p-2" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
        
                    <!-- Nombre -->
                    <div class="mb-3">
                        <label for="id_nombre" class="form-label justify-content-center d-flex text-white ">Nombre</label>
                        {{ form.nombre }}
                    </div>
        
                    <!-- Local -->
                    <div class="form-group">
                        <label for="id_local" class="form-label justify-content-center d-flex text-white ">Local</label>
                        {{ form.local }}
                    </div>
        
                    <!-- Imagen -->
                    <div class="mb-3">
                        <div class="form-group" >
                            <label for="id_imagenes" class="form-label justify-content-center d-flex text-white" >Imágenes</label>
                            {{ form.imagenes }}
                        </div>
                    </div>
                    <!-- Canción -->
                    <table class="table table-dark table-striped">
                        <thead>
                            <tr>
                                <th>Imagen</th>
                                <th>Título</th>
                                <th>Seleccionar</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for cancion in canciones %}
                                <tr>
                                    <td><img src="{{ cancion.imagen_url }}" alt="{{ cancion.titulo }}" style="width:50px; height:50px;"></td>
                                    <td>{{ cancion.titulo }}</td>
                                    <td>
                                        <input 
                                            type="checkbox" 
                                            name="canciones" 
                                            value="{{ cancion.id }}" 
                                            class="cancion-checkbox" 
                                            onchange="limitSelection(this)">
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                    <script>
                        function limitSelection(checkbox) {
                            const maxSelection = 3;
                            const checkboxes = document.querySelectorAll('.cancion-checkbox:checked');
                            if (checkboxes.length > maxSelection) {
                                alert(`Solo puedes seleccionar hasta ${maxSelection} canciones.`);
                                checkbox.checked = false;
                            }
                        }
                    </script>
                    <!-- Botón de envío -->
                    <div class="form-group justify-content-center d-flex">
                        <button type="submit" class="btn btn-outline-light mb-3">Guardar Usuario</button>
                    </div>
                </form>
            </div>
          </div>
          <div class="col-4"></div>
        </div>
    </div>
</body>
</html>